### ISSUE TITLE
Importing library results in Uncaught TypeError

### ISSUE THREAD

**Issue by Maikkeyy** [ESD6-blockr/blockr-crypto#5]
![image](https://user-images.githubusercontent.com/19424609/58432864-dc4ccc80-80b4-11e9-9cf8-f946def542b0.png)

Version: 1.0.0-1

Any ideas?

**Comment by saltz** [comment]
Because the library makes use of dependency injection which has a downstream dependency on `reflect-metadata` this error is thrown. So in order to fix your issue, you should add the dependency:

`"reflect-metadata": "^0.1.13"`

And add the following import on your main startup class/ function:
`import "reflect-metadata"`

**Comment by Maikkeyy** [comment]
Thanks!
